# Generated by Django 3.1.3 on 2020-12-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='site_url',
            field=models.URLField(max_length=1024),
        ),
    ]
