# Generated by Django 3.1.3 on 2020-12-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='images',
            name='color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='images',
            name='imgid',
            field=models.CharField(blank=True, default=None, max_length=126, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='imgurl',
            field=models.URLField(default=None, max_length=1024),
        ),
        migrations.AddField(
            model_name='images',
            name='notes',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='images',
            name='panorama',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='images',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='images',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
        ),
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='images',
            name='uploaded_by',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
