# Generated by Django 3.1.3 on 2021-01-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_presentation', '0003_auto_20201214_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='purchasable/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='imgurl',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
